export const Courses = [
  {
    id: 0,
    name: 'Knowledge representation and reasoning',
    description: 'Knowledge representation and reasoning',
    abbreviation: 'KnowRepReas',
    year: 2019,
    courseId: 0,
    enrolled: true,
    instructor: false,
    admin: true,
  },
  {
    id: 1,
    name: 'Princípy databáz',
    description: 'Naučíte sa princípy databáz ;)',
    abbreviation: 'Databazy',
    year: 2019,
    courseId: 1,
    enrolled: false,
    instructor: false,
    admin: false,
  },
  {
    id: 2,
    name: 'Web design Technology and Methodology',
    description: 'Web design in a nutshell',
    abbreviation: 'WebDesign',
    year: 2019,
    courseId: 4,
    enrolled: false,
    instructor: true,
    admin: false,
  },
  {
    id: 3,
    name: 'Computational Logic',
    description: 'Computational Logic for beginners',
    abbreviation: 'CompLogic',
    year: 2018,
    courseId: 3,
    enrolled: false,
    instructor: false,
    admin: true,
  },
  {
    id: 4,
    name: 'Web design Technology and Methodology',
    description: 'Web design in a nutshell',
    abbreviation: 'WebDesign',
    year: 2017,
    courseId: 4,
    enrolled: false,
    instructor: true,
    admin: false,
  },
  {
    id: 5,
    name: 'Computational Logic',
    description: 'Computational Logic for beginners',
    abbreviation: 'CompLogic',
    year: 2017,
    courseId: 3,
    enrolled: false,
    instructor: false,
    admin: true,
  },
  {
    id: 7,
    name: 'Computational Logic',
    description: 'Computational Logic for beginners',
    abbreviation: 'CompLogic',
    year: 2016,
    courseId: 3,
    enrolled: false,
    instructor: false,
    admin: true,
  },
  {
    id: 8,
    name: 'Web design Technology and Methodology',
    description: 'Web design in a nutshell',
    abbreviation: 'WebDesign',
    year: 2018,
    courseId: 4,
    enrolled: false,
    instructor: true,
    admin: false,
  },
  {
    id: 9,
    name: 'Computational Logic',
    description: 'Computational Logic for beginners',
    abbreviation: 'CompLogic',
    year: 2019,
    courseId: 3,
    enrolled: false,
    instructor: false,
    admin: true,
  },
]

const Courses2 = [
  {
    name: 'Knowledge representation and reasoning',
    description: 'Knowledge representation and reasoning',
    abbreviation: 'KnowRepReas',
    hasPrerequisite: [],
    mentions: [],
    covers: [],
  },
  {
    name: 'Computational Logic',
    description: 'Computational Logic for beginners',
    abbreviation: 'CompLogic',
    hasPrerequisite: [],
    mentions: [],
    covers: [],
  },
  {
    name: 'Web design Technology and Methodology',
    description:
      'Web design encompasses many different skills and disciplines ' +
      'in the production and maintenance of websites. The different areas of web design ' +
      'include web graphic design; interface design; authoring, including standardised code ' +
      'and proprietary software; user experience design; and search engine optimization.',
    abbreviation: 'WebDesign',
    hasPrerequisite: [],
    mentions: [],
    covers: [ 'w14DB', 'PQXeT', 'NuUyB', 'zP0ri' ],
  },
  {
    name: 'Princípy databáz',
    description: 'Naučíte sa princípy databáz ;)',
    abbreviation: 'Databazy',
    hasPrerequisite: [],
    mentions: [],
    covers: [],
  },
]
