name: Configure apache

on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      BASE_WEBSITE_PORT:
        required: true
        type: number
      PR_NUMBER:
        required: false
        type: string
        default: "0"
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  configure-apache:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate PR port
        run: echo "PR_PORT_PART=$(printf "%03i" ${{ inputs.PR_NUMBER }} | tail -c 4)" >> $GITHUB_ENV
      - name: Calculate Website port
        run: echo "WEBSITE_PORT=$(expr ${{ inputs.BASE_WEBSITE_PORT }} + ${{ env.PR_PORT_PART }})" >> $GITHUB_ENV
      - name: Configure apache
        uses: appleboy/ssh-action@master
        env:
          BRANCH: ${{ inputs.BRANCH }}
          PORT: ${{ env.WEBSITE_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: BRANCH, PORT
          script: ./createConfig.sh ${BRANCH} ${PORT}
