name: MW - Clean up after PR is closed

on: 
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  remove-frontend-directory:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    uses: matfyz-sk/courses-frontend/.github/workflows/remove-destination.yml@master
    with:
      FRONTEND_PATH: /home/www/devcourses3.matfyz.sk/
      PR_BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
  remove-backend:
    if: ${{ github.event.label.name == 'master backend' }}
    uses: matfyz-sk/courses-backend/.github/workflows/remove-backend.yml@master
    with:
      BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
  clean-apache:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    uses: matfyz-sk/courses-frontend/.github/workflows/clean-apache.yml@master
    with:
      BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}