name: Deployment of frontend

on:
  workflow_call:
    inputs:
      FOLDER:
        required: true
        type: string
      WEBSITE_PORT:
        required: true
        type: number
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      WEBSITE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: matfyz-sk/courses-frontend
      - name: Setup nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Creating react env file
        env:
          WEBSITE: ${{ secrets.WEBSITE }}
          WEBSITE_PORT: ${{ inputs.WEBSITE_PORT}}
        run: echo "REACT_APP_BACKEND_URL=$WEBSITE:$WEBSITE_PORT" >> .env
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test --passWithNoTests
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'placeholder'
      - name:  Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: rsync -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ inputs.FOLDER }}
