name: MW - Deployment of testing enviroment for new or updated PR 

on: 
  pull_request:
    types: [opened, reopened, labeled, edited, synchronized]
  workflow_dispatch:

jobs:
  create-frontend-directory:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    uses: matfyz-sk/courses-frontend/.github/workflows/create-destination.yml@master
    with:
      FRONTEND_PATH: /home/www/devcourses3.matfyz.sk/
      PR_BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      IMPERSONATION_PASSWORD: ${{ secrets.IMPERSONATION_PASSWORD }}
      JDBC_PORT: ${{ secrets.JDBC_PORT }}
      OWNER: ${{ secrets.OWNER }}
      OWNER_ACCESS_TOKEN: ${{ secrets.OWNER_ACCESS_TOKEN }}
      SPARQL_HOST: ${{ secrets.SPARQL_HOST }}
      SPARQL_PASSWORD: ${{ secrets.SPARQL_PASSWORD }}
      SPARQL_USER: ${{ secrets.SPARQL_USER }}
      SUPER_ADMIN_EMAIL: ${{ secrets.SUPER_ADMIN_EMAIL }}
      SSH_USSUPER_ADMIN_NAME: ${{ secrets.SUPER_ADMIN_NAME }}
      SUPER_ADMIN_PASSWORD: ${{ secrets.SUPER_ADMIN_PASSWORD }}
      WEBSITE: ${{ secrets.WEBSITE }}
  deploy-frontend:
    if: contains(github.event.pull_request.labels.*.name, 'master backend')
    needs: create-frontend-directory
    uses: matfyz-sk/courses-frontend/.github/workflows/deploy.yml@master
    with:
      BRANCH: ${{ github.event.pull_request.head.ref }}
      FRONTEND_PATH: /home/www/devcourses3.matfyz.sk/
      BASE_WEBSITE_PORT: 10000
      PR_NUMBER: ${{ github.event.number }}
      PR_BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WEBSITE: ${{ secrets.WEBSITE }}
  config-apache:
    if: contains(github.event.pull_request.labels.*.name, 'master backend')
    needs: [create-frontend-directory, deploy-frontend]
    uses: matfyz-sk/courses-frontend/.github/workflows/apache.yml@master
    with:
      BRANCH: ${{ github.event.pull_request.head.ref }}
      BASE_WEBSITE_PORT: 10000
      PR_NUMBER: ${{ github.event.number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
  get-pr-number:
    if: contains(github.event.pull_request.labels.*.name, 'branch backend')
    uses: matfyz-sk/courses-frontend/.github/workflows/get-pr-number.yml@master
    with:
      BRANCH: ${GITHUB_HEAD_REF}
  deploy-frontend-with-backend-pr:
    if: contains(github.event.pull_request.labels.*.name, 'branch backend')
    needs: [create-frontend-directory, get-pr-number]
    uses: matfyz-sk/courses-frontend/.github/workflows/deploy.yml@master
    with:
      BRANCH: ${{ github.event.pull_request.head.ref }}
      FRONTEND_PATH: /home/www/devcourses3.matfyz.sk/
      BASE_WEBSITE_PORT: 9000
      PR_NUMBER: ${{ needs.get-pr-number.outputs.pr-number }}
      PR_BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WEBSITE: ${{ secrets.WEBSITE }}
  config-apache-with-backend-pr:
    if: contains(github.event.pull_request.labels.*.name, 'branch backend')
    needs: [create-frontend-directory, get-pr-number, deploy-frontend-with-backend-pr]
    uses: matfyz-sk/courses-frontend/.github/workflows/apache.yml@master
    with:
      BRANCH: ${{ github.event.pull_request.head.ref }}
      BASE_WEBSITE_PORT: 9000
      PR_NUMBER: ${{ needs.get-pr-number.outputs.pr-number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}