name: release

env:
  FOLDER: /home/www/devcourses3.matfyz.sk/

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test --passWithNoTests
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'placeholder'
      - name:  Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Trigger and wait backend workflow
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ secrets.OWNER }}
          wait_interval: 60
          repo: courses-backend
          github_token: ${{ secrets.OWNER_ACCESS_TOKEN }}
          workflow_file_name: release.yml
      - name: Deploy
        run: rsync -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$FOLDER
      

