name: Remove directories on frontend path

on:
  workflow_call:
    inputs:
      FRONTEND_PATH:
        required: true
        type: string
      PR_BRANCH:
        required: false
        type: string
        default: ''
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  remove-destination:
    runs-on: ubuntu-latest
    steps:
      - name: Use passed frontend path
        if: ${{ inputs.PR_BRANCH == ''}}
        run: echo "FRONTEND_PATH=${{ inputs.FRONTEND_PATH }}" >> $GITHUB_ENV
      - name: Create path to the frontend
        if: ${{ inputs.PR_BRANCH != ''}}
        run: echo "FRONTEND_PATH=${{ inputs.FRONTEND_PATH }}${{ inputs.PR_BRANCH }}/htdocs/" >> $GITHUB_ENV
      - name: Remove frontend folder
        uses: appleboy/ssh-action@master
        env:
          FRONTEND_PATH: ${{ env.FRONTEND_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: FRONTEND_PATH
          script: rm --force --recursive --dir ${FRONTEND_PATH}
