name: Deployment of testing enviroment

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy-frontend:
    uses: matfyz-sk/courses-frontend/.github/workflows/deploy.yml@master
    with:
      FOLDER: /home/www/devcourses3.matfyz.sk/
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
  deploy-backend:
    uses: matfyz-sk/courses-backend/.github/workflows/deploy.yml@master
    with:
      TAG: courses:testing
      CONTAINER: courses-testing
      BRANCH: ${GITHUB_REF##*/}
      PORT: 4000:4000
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}



